  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"
  url = "/en/portfolio/"

  [[main]]
  name = "Articles"
  weight = 300
  identifier = "posts"
  url = "/en/post/"

  [[main]]
  name = "Manifesto"
  weight = 400
  identifier = "about"
  url = "/en/manifesto/"

 [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/en/contact/"

  [[footer]]
  name = "imprint"
  weight = 2
  identifier = "imprint"
  url = "/en/imprint/"

  [[footer]]
  name = "Contact"
  weight = 1
  identifier = "contact"
  url = "/en/contact/"
