
title = "Chaotique professionnel"
author = "Mathieu Prost"
#copyright = "2020-2021"
description = "Appelez moi Mat, et commandez moi un café"
profilePicture = "images/portrait.svg"
keywords = "Mathieu Prost, Marketing Dijon, Freelance Marketing"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
#n8n webhook (originally contact form spree)
contactFormAction = "https://flow.mathieuprost.fr/webhook/a7459b35-fc73-4b58-ac0f-27b29964cadc"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
googleFonts = ["Space+Grotesk:wght@400;700", "Inter:wght@300;400;500;600;700"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3

# Full link to license
#license = "https://creativecommons.org/licenses/by/4.0/"

# disableTitleCapitalization = true

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

# Sidebar/Content Ratio
# contentratio = 0.6

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

## Social links
# use 'fa-brands' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/mathieu-prost/"

[[socialIcons]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/MetaphorSuit"

#[[socialIcons]]
#icon = "fa-brands fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[socialIcons]]
icon = "fa-solid fa-envelope"
title = "e-mail"
url = "mailto:mprost.contact@gmail.com"

[mermaid]
# enable = true
